[build-system]
requires = ["hatchling", "uv-dynamic-versioning"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.uv-dynamic-versioning]
vcs = "git"
style = "pep440"
bump = true

[project]
name = "dbos-crewai"
dynamic = ["version"]
description = "CrewAI DBOS durable agent"
authors = [
    { name = "Qian Li", email = "qian.li@dbos.dev" },
]
license = "MIT"
license-files = ["LICENSE"]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "crewai>=1.2.1",
    "dbos>=2.3.0",
]

[project.urls]
Homepage = "https://dbos.dev"
Source = "https://github.com/dbos-inc/dbos-crewai"
Documentation = "https://docs.dbos.dev"

[tool.hatch.build]
packages = ["dbos_crewai"]

[tool.hatch.build.targets.wheel]
only-include = ["README.md"]

[tool.hatch.build.targets.sdist]
include = ["README.md", "tests"]

[dependency-groups]
dev = [
    "isort>=7.0.0",
    "pre-commit>=4.3.0",
    "pytest>=8.4.2",
    "pytest-vcr>=1.0.2",
    "ruff>=0.14.2",
]
